#!/bin/bash

if [[ ! -d "/workspaces/DogBot/ros2_ws" ]]; then
    echo "> ERROR: Workspace not found: /workspaces/DogBot/ros2_ws"
    exit 1
fi

cd "/workspaces/DogBot/ros2_ws" || exit 1

colcon build --symlink-install