#!/bin/bash

: "${DOGBOT_PATH:=/workspaces/DogBot}"

if [[ -z "${DOGBOT_PATH}" || "${DOGBOT_PATH}" == "/" ]]; then
    echo "Invalid DOGBOT_PATH: '${DOGBOT_PATH}'"
    exit 1
fi

rm -rf -- \
    "${DOGBOT_PATH}/ros2_ws/build" \
    "${DOGBOT_PATH}/ros2_ws/install" \
    "${DOGBOT_PATH}/ros2_ws/log"
