color_detect_nonblue:
  ros__parameters:
    # 识别模式：0=禁用，1=HSV，2=RGB，3=LAB
    mode: 3
    min_area: 5000

    # HSV 模式参数（mode=1 时生效），与 color_detect_nonblue.cpp 默认值一致
    hsv_red_lower1: [0, 120, 70] #(0,162,186)
    hsv_red_upper1: [10, 255, 255]
    hsv_red_lower2: [170, 120, 70]
    hsv_red_upper2: [179, 255, 255]
    hsv_green_lower1: [40, 50, 50] #(46,116,242)
    hsv_green_upper1: [80, 255, 255] 
    hsv_brown_lower1: [10, 50, 30] #(2,156,88)
    hsv_brown_upper1: [25, 255, 180]
    hsv_purple_lower1: [130, 50, 50] #(136,115,134)
    hsv_purple_upper1: [160, 255, 255]
    hsv_orange_lower1: [5, 120, 70] #(24,103,255)
    hsv_orange_upper1: [18, 255, 255]

    # RGB 模式参数（mode=2 时生效），color 为 [R,G,B] 顺序
    rgb_red_color: [118, 183, 156]
    rgb_red_tolerance: 10
    rgb_green_color: [236, 89, 177]
    rgb_green_tolerance: 10
    rgb_brown_color: [54, 153, 143]
    rgb_brown_tolerance: 10
    rgb_purple_color: [82, 155, 99]
    rgb_purple_tolerance: 10
    rgb_orange_color: [240, 122, 170]
    rgb_orange_tolerance: 10

    # LAB 模式参数（mode=3 时生效），color 为 [L,a,b] 顺序（OpenCV CV_8U，0-255）
    lab_red_color: [194,166, 144] #194,158,130
    lab_red_tolerance: 0
    lab_green_color: [245, 97, 170]
    lab_green_tolerance: 15
    lab_brown_color: [148, 175, 152]
    lab_brown_tolerance: 15
    lab_purple_color: [194, 167, 99]
    lab_purple_tolerance: 20
    lab_orange_color: [235, 127, 154]
    lab_orange_tolerance: 15
