leg_controller:
  ros__parameters:
    thigh_length: 0.08955
    calf_length: 0.09054
    hip_offset: 0.0 #0.752
    L3: 0.0772
    L4: 0.02383
    L5: 0.075
    servo_arm: 0.02355
    rocker_offset: -2.70
    fork_branch: true
    gait_period: 0.6
    step_height: 0.03
    gait_mode: trot
    stance_y: 0.0
    stance_z: 0.13